//! macOS clipboard reader. Structured against the documented AppKit API but
//! untested on hardware, per the v0.1 scope.

use super::types::{PollState, Snapshot};
use objc2::rc::autoreleasepool;
use objc2_app_kit::{NSPasteboard, NSPasteboardTypePNG, NSPasteboardTypeString, NSPasteboardTypeTIFF, NSWorkspace};
use objc2_foundation::NSString;

/// Markers that mean "do not record this". The first is the cross-app
/// convention honoured by password managers; the second marks throwaway
/// content that is not worth a history entry.
const CONCEALED_TYPES: &[&str] = &[
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
];

pub fn poll(state: &mut PollState) -> Snapshot {
    autoreleasepool(|_| unsafe {
        let pb = NSPasteboard::generalPasteboard();
        let seq = pb.changeCount() as u64;

        if state.primed && seq == state.last_change {
            return Snapshot::Unchanged;
        }
        state.last_change = seq;

        if !state.primed {
            state.primed = true;
            return Snapshot::Unchanged;
        }

        // Checked before any content is read, same as the Windows path.
        if let Some(types) = pb.types() {
            for t in types.iter() {
                let name = t.to_string();
                if CONCEALED_TYPES.contains(&name.as_str()) {
                    return Snapshot::Concealed;
                }
            }
        }

        if let Some(s) = pb.stringForType(NSPasteboardTypeString) {
            let text = s.to_string();
            if !text.is_empty() {
                return Snapshot::Text(text);
            }
        }

        if let Some(png) = pb.dataForType(NSPasteboardTypePNG) {
            return image_snapshot(png.bytes().to_vec(), false);
        }

        if let Some(tiff) = pb.dataForType(NSPasteboardTypeTIFF) {
            return image_snapshot(tiff.bytes().to_vec(), true);
        }

        Snapshot::Unsupported
    })
}

/// TIFF is re-encoded to PNG so stored images have one format and one stable
/// hash across source apps.
fn image_snapshot(bytes: Vec<u8>, needs_reencode: bool) -> Snapshot {
    if bytes.len() > super::types::MAX_IMAGE_BYTES {
        tracing::debug!(bytes = bytes.len(), "clipboard image over limit; skipped");
        return Snapshot::Unsupported;
    }
    if !needs_reencode {
        return Snapshot::Image(bytes);
    }
    match super::reencode_to_png(&bytes) {
        Some(png) => Snapshot::Image(png),
        None => Snapshot::Unsupported,
    }
}

pub fn foreground_app() -> Option<String> {
    autoreleasepool(|_| unsafe {
        let app = NSWorkspace::sharedWorkspace().frontmostApplication()?;
        app.localizedName().map(|n: objc2::rc::Retained<NSString>| n.to_string())
    })
}
